spring:
  security:
    oauth2:
      client:
        registration:
          akun:
            client-id: akun-client-id
            client-secret: akun-client-secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-name: Akun
            client-alias: akun

        provider:
          akun:
            authorization-uri: https://akun-kp.cs.ui.ac.id/cas/oauth2.0/authorize
            token-uri: https://akun-kp.cs.ui.ac.id/cas/oauth2.0/accessToken
            user-info-uri: https://akun-kp.cs.ui.ac.id/cas/oauth2.0/profile
            user-name-attribute: id
